### ISSUE TITLE
Ubuntu 20.04 support (thanks for awesome app)

### ISSUE THREAD

**Issue by rjccosta1** [slimbook/slimbookbattery#17]
Ubuntu 20.04 is around the corner. We need support for it.

**Comment by slimbook** [comment]
Thanks, we are working on it.

**Comment by isene** [comment]
After upgrading to 20.04, I can no longer change the mode - it is stuck on "Balanced".

**Comment by slimbook** [comment]
Hello, please, purge an install again.

**Comment by isene** [comment]
I had to manually remove /usr/share/slimbookbattery and the files in there - then the reinstall worked :-)

**Comment by isene** [comment]
Maybe not something you can answer, but I'll try anyhow - upgrading from 19.10 to 20.04 my power drain (with slimbookbattery running in energy saving mode) went from around 9W to 13W. Any way to get that back down?

**Comment by slimbook** [comment]
It would be useful to know what is happening in the operating system. What processes are in the background, what kernel version, if changed the brightness of the screen, etc.

**Comment by isene** [comment]
Upgrading from Ubuntu 19.10 to 20.04 on my Dell XPS15 laptop without touch screen.
Basically everything is the same as with 19.10 (screen brightness, apps running, etc.)
uname -a: Linux 5.4.0-33-generic #37-Ubuntu SMP

Running at startup:
  tlp start
  slimbookbattery
  pm-powersave true
  powertop --auto-tune

CPU load seems to be the same, memory used is the same, but system load seems a bit higher (0.2 - 0.3 as compared to 0.1 - 0.2)... The main load is on qutebrowser (as before) with its qt dependencies - but this should not push the battery drain up 4W in any case. powertop reports:

While writing this, I went into powertop and see this crazy culprit:
  10.8 W      7,7 pkts/s                Device         Network interface: wlp2s0 (ath10k_pci)

Now, that's the root cause methinks. But I have no idea how to push that down.

**Comment by isene** [comment]
I should add that on 19.10, the wlp2s0 (ath10k_pci) reported around 6W in powertop.

**Comment by isene** [comment]
Additional info that may be directly pertinent to slimbookbattery: As my battery percentage now dropped to 12%, all of a sudden my powerdrain dropped to where it used to be under 19.10 (or even a bit lower) - between 7W and 8W total. Now this is where I would like it to be - I need maximum battery capacity, not computing power (in most cases).

**Comment by slimbook** [comment]
Hello 

Using powertop --auto-tune is not recommended because among other things, it tends to enable selective USB suspension by default that can be very annoying when using external input devices and nasty file corruption on some USB thumbdrives.

Maybe you should take a look at which kernel were you using in 19.10 and check if it's the same in 20.04. 

Other than that, we are unable to test your actual network interface power draws because we don't have any Dell computers here.

**Comment by isene** [comment]
OK, thanks for the tips. My case is closed here :-)
